name: Run Tests with uv pytest

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        run: pip install uv
      - name: Install dependencies with uv
        run: uv sync --all-extras
      - name: Run ruff check
        run: ruff check .
      - name: mypy src tests
        run: mypy src tests
      - name: Run tests with uv pytest
        run: uv run --locked pytest
